[book]
authors = ["Arden Rasmussen"]
language = "en"
multilingual = false
src = "src"
title = "Physically Based Rendering"
[build]
build-dir="docs"
[output.html]
theme = "src/theme"
curly-quotes = true
mathjax-support = true
git-repository-url = "https://github.com/LuxAter/Specula.git"
